required = [
  "github.com/golang/lint/golint",
  "golang.org/x/tools/cmd/goimports",
]

[[constraint]]
  name = "github.com/kubernetes-incubator/service-catalog"
  version = "0.1.32"

[[constraint]]
  branch = "master"
  name = "github.com/kyma-project/kyma"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "github.com/satori/go.uuid"
  version = "1.2.0"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.6"

[[constraint]]
  name = "github.com/vrischmann/envconfig"
  version = "1.1.0"

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.11.0"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.11.0"

[[constraint]]
  name = "k8s.io/client-go"
  version = "8.0.0"

[prune]
  go-tests = true
  unused-packages = true
