replicaCount: 1
image:
  repository: eu.gcr.io/kyma-project/incubator/develop/service-catalog-tester
  tag: 3c2be629
  pullPolicy: IfNotPresent

app:
  port: "8080"
  loggingLevel: "info"

slackClient:
  webhookUrl: ""
  channelId: ""
  token: ""

observableDeployments:
  namespace: ""
  names: "core-catalog-apiserver,core-catalog-controller-manager"

e2eServiceCatalogHappyPath:
  testThrottle: "60s"
  testOnlyServiceCatalog: "false"

clusterName: ""
