kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ template "stressor.fullname" . }}
  labels:
    app: {{ template "stressor.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
rules:
- apiGroups: ["servicecatalog.k8s.io"]
  resources: ["serviceinstances", "servicebindings"]
  verbs: ["get", "delete", "create"]
- apiGroups: ["servicecatalog.kyma.cx"]
  resources: ["servicebindingusages"]
  verbs: ["get", "delete", "create"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["create", "delete", "get"]
- apiGroups: [""]
  resources: ["services", "namespaces"]
  verbs: ["create", "delete", "get", "list"]
- apiGroups: [""]
  resources: ["pods", "pods/log", "events"]
  verbs: ["get", "list", "watch"]
