apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "stressor.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "stressor.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
